### ISSUE TITLE
 What about sandbox?

### ISSUE THREAD

**Issue by AgelxNash** [nk2ge5k/yandex-direct-api#1]
directapi\DirectApiService::$apiUrl is private and can't be changed to https://api-sandbox.direct.yandex.com/json/v5/

**Comment by nk2ge5k** [comment]
Fixed:
https://github.com/nk2ge5k/yandex-direct-api/commit/e637c22e3d9b1ba3590de5b9762c366e229edc94

**Comment by AgelxNash** [comment]
This commit is't compatibility with PHP 5.6

``` php
public function setSandbox ( bool $sandbox = TRUE );
public function useOperatorPoints( bool $use );
```
