### ISSUE TITLE
Use-Operator-Units

### ISSUE THREAD

**Issue by AgelxNash** [nk2ge5k/yandex-direct-api#3]
Header **Use-Operator-Units** can set only if useOperatorPoints property is false
💩 Yandex

**Comment by nk2ge5k** [comment]
Ничего не понял

**Comment by AgelxNash** [comment]
Заголовок **Use-Operator-Units** можно использовать только если свойство useOperatorPoints установлено как false, в случае если доступ осуществляется средствами клиента.
При попытке установить true получаем ошибку от яндекса

```
Некорректный запрос. Использование HTTP-заголовка Use-Operator-Units доступно только агентствам (campaigns, get)
```

**Comment by nk2ge5k** [comment]
Но это логично, если у вас не агенсткий аккаунт.

**Comment by AgelxNash** [comment]
И тем не менее, Use-Operator-Units устанавливается всегда true/false. Яндекс же ругается на этот заголовок в значении false

**Comment by nk2ge5k** [comment]
Я могу разве что убрать его в случае если он не устанавливался.

**Comment by AgelxNash** [comment]
Я это и имел в виду

**Comment by nk2ge5k** [comment]
Fixed:
0c480fcca65c074c1358d43d3ee585432bd7eb12
