### ISSUE TITLE
Поддержка Сервиса Reports

### ISSUE THREAD

**Issue by G1K** [nk2ge5k/yandex-direct-api#6]
Недавно Яндекс предоставил новый сервис, позволяющий в TSV получать отчеты.
@link https://tech.yandex.ru/direct/doc/reports/reports-docpage/

Планируете ли двигаться в этом направлении ? )

**Comment by nk2ge5k** [comment]
Да, но я предполагаю, что это будет отдельная библиотека.

**Comment by AgelxNash** [comment]
@nk2ge5k Можно ли уже с этой библиотекой познакомиться?
@G1K Удалось ли найти библиотеку поддерживающую отчеты?

**Comment by G1K** [comment]
@AgelxNash да получилось найти. Совсем недавно ребята выпустили достаточно красивую реализацию.
https://github.com/biplane/yandex-direct

**Comment by nk2ge5k** [comment]
Я сомневаюсь, что к этой библиотеке я когда-нибудь что-нибудь допишу. Потому что у меня есть другая реализация, но по причине того, что она написана для работы мне не разрешенно ее выкладывать в гитхаб. Извиняюсь
